/*
 * Copyright 2009-2017 Alibaba Cloud All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <alibabacloud/outboundbot/model/ListAnnotationMissionSessionResult.h>
#include <json/json.h>

using namespace AlibabaCloud::OutboundBot;
using namespace AlibabaCloud::OutboundBot::Model;

ListAnnotationMissionSessionResult::ListAnnotationMissionSessionResult() :
	ServiceResult()
{}

ListAnnotationMissionSessionResult::ListAnnotationMissionSessionResult(const std::string &payload) :
	ServiceResult()
{
	parse(payload);
}

ListAnnotationMissionSessionResult::~ListAnnotationMissionSessionResult()
{}

void ListAnnotationMissionSessionResult::parse(const std::string &payload)
{
	Json::Reader reader;
	Json::Value value;
	reader.parse(payload, value);
	setRequestId(value["RequestId"].asString());
	auto dataNode = value["Data"];
	if(!dataNode["AnnotationMissionId"].isNull())
		data_.annotationMissionId = dataNode["AnnotationMissionId"].asString();
	if(!dataNode["Success"].isNull())
		data_.success = dataNode["Success"].asString() == "true";
	if(!dataNode["Message"].isNull())
		data_.message = dataNode["Message"].asString();
	if(!dataNode["TotalCount"].isNull())
		data_.totalCount = std::stol(dataNode["TotalCount"].asString());
	auto allAnnotationMissionSessionListNode = dataNode["AnnotationMissionSessionList"]["AnnotationMissionSessionListItem"];
	for (auto dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem : allAnnotationMissionSessionListNode)
	{
		Data::AnnotationMissionSessionListItem annotationMissionSessionListItemObject;
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["AnnotationMissionSessionId"].isNull())
			annotationMissionSessionListItemObject.annotationMissionSessionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["AnnotationMissionSessionId"].asString();
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["CreateTime"].isNull())
			annotationMissionSessionListItemObject.createTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["CreateTime"].asString());
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["ModifiedTime"].isNull())
			annotationMissionSessionListItemObject.modifiedTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["ModifiedTime"].asString());
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["AnnotationMissionId"].isNull())
			annotationMissionSessionListItemObject.annotationMissionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["AnnotationMissionId"].asString();
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["InstanceId"].isNull())
			annotationMissionSessionListItemObject.instanceId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["InstanceId"].asString();
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["ScriptId"].isNull())
			annotationMissionSessionListItemObject.scriptId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["ScriptId"].asString();
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["JobGroupId"].isNull())
			annotationMissionSessionListItemObject.jobGroupId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["JobGroupId"].asString();
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["JobId"].isNull())
			annotationMissionSessionListItemObject.jobId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["JobId"].asString();
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["SessionId"].isNull())
			annotationMissionSessionListItemObject.sessionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["SessionId"].asString();
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["AnnotationStatus"].isNull())
			annotationMissionSessionListItemObject.annotationStatus = std::stoi(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["AnnotationStatus"].asString());
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["Version"].isNull())
			annotationMissionSessionListItemObject.version = std::stoi(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["Version"].asString());
		if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["DebugConversation"].isNull())
			annotationMissionSessionListItemObject.debugConversation = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["DebugConversation"].asString() == "true";
		auto allAnnotationMissionChatListNode = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItem["AnnotationMissionChatList"]["AnnotationMissionChatListItem"];
		for (auto dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem : allAnnotationMissionChatListNode)
		{
			Data::AnnotationMissionSessionListItem::AnnotationMissionChatListItem annotationMissionChatListObject;
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationMissionChatId"].isNull())
				annotationMissionChatListObject.annotationMissionChatId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationMissionChatId"].asString();
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["CreateTime"].isNull())
				annotationMissionChatListObject.createTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["CreateTime"].asString());
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["ModifiedTime"].isNull())
				annotationMissionChatListObject.modifiedTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["ModifiedTime"].asString());
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationMissionId"].isNull())
				annotationMissionChatListObject.annotationMissionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationMissionId"].asString();
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationMissionSessionId"].isNull())
				annotationMissionChatListObject.annotationMissionSessionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationMissionSessionId"].asString();
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["InstanceId"].isNull())
				annotationMissionChatListObject.instanceId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["InstanceId"].asString();
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["SequenceId"].isNull())
				annotationMissionChatListObject.sequenceId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["SequenceId"].asString();
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["OccurTime"].isNull())
				annotationMissionChatListObject.occurTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["OccurTime"].asString());
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["Answer"].isNull())
				annotationMissionChatListObject.answer = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["Answer"].asString();
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationStatus"].isNull())
				annotationMissionChatListObject.annotationStatus = std::stoi(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationStatus"].asString());
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["IntentAnnotationStatus"].isNull())
				annotationMissionChatListObject.intentAnnotationStatus = std::stoi(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["IntentAnnotationStatus"].asString());
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AsrAnnotationStatus"].isNull())
				annotationMissionChatListObject.asrAnnotationStatus = std::stoi(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AsrAnnotationStatus"].asString());
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["TagAnnotationStatus"].isNull())
				annotationMissionChatListObject.tagAnnotationStatus = std::stoi(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["TagAnnotationStatus"].asString());
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["SubStatus"].isNull())
				annotationMissionChatListObject.subStatus = std::stoi(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["SubStatus"].asString());
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["TranslationError"].isNull())
				annotationMissionChatListObject.translationError = std::stoi(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["TranslationError"].asString());
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationAsrResult"].isNull())
				annotationMissionChatListObject.annotationAsrResult = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationAsrResult"].asString();
			if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["OriginalAsrResult"].isNull())
				annotationMissionChatListObject.originalAsrResult = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["OriginalAsrResult"].asString();
			auto allAnnotationMissionChatIntentUserSayInfoListNode = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationMissionChatIntentUserSayInfoList"]["AnnotationMissionChatIntentUserSayInfoListItem"];
			for (auto dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem : allAnnotationMissionChatIntentUserSayInfoListNode)
			{
				Data::AnnotationMissionSessionListItem::AnnotationMissionChatListItem::AnnotationMissionChatIntentUserSayInfoListItem annotationMissionChatIntentUserSayInfoListObject;
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["AnnotationMissionChatIntentUserSayInfoId"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.annotationMissionChatIntentUserSayInfoId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["AnnotationMissionChatIntentUserSayInfoId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["CreateTime"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.createTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["CreateTime"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["ModifiedTime"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.modifiedTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["ModifiedTime"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["InstanceId"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.instanceId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["InstanceId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["AnnotationMissionId"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.annotationMissionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["AnnotationMissionId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["AnnotationMissionSessionId"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.annotationMissionSessionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["AnnotationMissionSessionId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["AnnotationMissionChatId"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.annotationMissionChatId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["AnnotationMissionChatId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["Content"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.content = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["Content"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["IntentId"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.intentId = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["IntentId"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["DialogId"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.dialogId = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["DialogId"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["BotId"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.botId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["BotId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["Delete"].isNull())
					annotationMissionChatIntentUserSayInfoListObject._delete = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["Delete"].asString() == "true";
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["Create"].isNull())
					annotationMissionChatIntentUserSayInfoListObject.create = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatIntentUserSayInfoListAnnotationMissionChatIntentUserSayInfoListItem["Create"].asString() == "true";
				annotationMissionChatListObject.annotationMissionChatIntentUserSayInfoList.push_back(annotationMissionChatIntentUserSayInfoListObject);
			}
			auto allAnnotationMissionChatVocabularyInfoListNode = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationMissionChatVocabularyInfoList"]["AnnotationMissionChatVocabularyInfoListItem"];
			for (auto dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem : allAnnotationMissionChatVocabularyInfoListNode)
			{
				Data::AnnotationMissionSessionListItem::AnnotationMissionChatListItem::AnnotationMissionChatVocabularyInfoListItem annotationMissionChatVocabularyInfoListObject;
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["AnnotationMissionChatVocabularyInfoId"].isNull())
					annotationMissionChatVocabularyInfoListObject.annotationMissionChatVocabularyInfoId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["AnnotationMissionChatVocabularyInfoId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["CreateTime"].isNull())
					annotationMissionChatVocabularyInfoListObject.createTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["CreateTime"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["ModifiedTime"].isNull())
					annotationMissionChatVocabularyInfoListObject.modifiedTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["ModifiedTime"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["InstanceId"].isNull())
					annotationMissionChatVocabularyInfoListObject.instanceId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["InstanceId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["AnnotationMissionId"].isNull())
					annotationMissionChatVocabularyInfoListObject.annotationMissionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["AnnotationMissionId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["AnnotationMissionSessionId"].isNull())
					annotationMissionChatVocabularyInfoListObject.annotationMissionSessionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["AnnotationMissionSessionId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["AnnotationMissionChatId"].isNull())
					annotationMissionChatVocabularyInfoListObject.annotationMissionChatId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["AnnotationMissionChatId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["VocabularyId"].isNull())
					annotationMissionChatVocabularyInfoListObject.vocabularyId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["VocabularyId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["Vocabulary"].isNull())
					annotationMissionChatVocabularyInfoListObject.vocabulary = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["Vocabulary"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["VocabularyName"].isNull())
					annotationMissionChatVocabularyInfoListObject.vocabularyName = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["VocabularyName"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["VocabularyDescription"].isNull())
					annotationMissionChatVocabularyInfoListObject.vocabularyDescription = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["VocabularyDescription"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["VocabularyWeight"].isNull())
					annotationMissionChatVocabularyInfoListObject.vocabularyWeight = std::stoi(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["VocabularyWeight"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["Delete"].isNull())
					annotationMissionChatVocabularyInfoListObject._delete = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["Delete"].asString() == "true";
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["Create"].isNull())
					annotationMissionChatVocabularyInfoListObject.create = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatVocabularyInfoListAnnotationMissionChatVocabularyInfoListItem["Create"].asString() == "true";
				annotationMissionChatListObject.annotationMissionChatVocabularyInfoList.push_back(annotationMissionChatVocabularyInfoListObject);
			}
			auto allAnnotationMissionChatCustomizationDataInfoListNode = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationMissionChatCustomizationDataInfoList"]["AnnotationMissionChatCustomizationDataInfoListItem"];
			for (auto dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem : allAnnotationMissionChatCustomizationDataInfoListNode)
			{
				Data::AnnotationMissionSessionListItem::AnnotationMissionChatListItem::AnnotationMissionChatCustomizationDataInfoListItem annotationMissionChatCustomizationDataInfoListObject;
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["AnnotationMissionChatCustomizationDataInfoId"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.annotationMissionChatCustomizationDataInfoId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["AnnotationMissionChatCustomizationDataInfoId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["CreateTime"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.createTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["CreateTime"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["ModifiedTime"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.modifiedTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["ModifiedTime"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["InstanceId"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.instanceId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["InstanceId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["AnnotationMissionId"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.annotationMissionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["AnnotationMissionId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["AnnotationMissionSessionId"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.annotationMissionSessionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["AnnotationMissionSessionId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["AnnotationMissionChatId"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.annotationMissionChatId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["AnnotationMissionChatId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["CustomizationDataId"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.customizationDataId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["CustomizationDataId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["Content"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.content = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["Content"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["CustomizationDataName"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.customizationDataName = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["CustomizationDataName"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["CustomizationDataDescription"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.customizationDataDescription = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["CustomizationDataDescription"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["CustomizationDataWeight"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.customizationDataWeight = std::stoi(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["CustomizationDataWeight"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["Delete"].isNull())
					annotationMissionChatCustomizationDataInfoListObject._delete = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["Delete"].asString() == "true";
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["Create"].isNull())
					annotationMissionChatCustomizationDataInfoListObject.create = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatCustomizationDataInfoListAnnotationMissionChatCustomizationDataInfoListItem["Create"].asString() == "true";
				annotationMissionChatListObject.annotationMissionChatCustomizationDataInfoList.push_back(annotationMissionChatCustomizationDataInfoListObject);
			}
			auto allAnnotationMissionChatTagInfoListNode = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItem["AnnotationMissionChatTagInfoList"]["AnnotationMissionChatTagInfoListItem"];
			for (auto dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem : allAnnotationMissionChatTagInfoListNode)
			{
				Data::AnnotationMissionSessionListItem::AnnotationMissionChatListItem::AnnotationMissionChatTagInfoListItem annotationMissionChatTagInfoListObject;
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionChatTagInfoId"].isNull())
					annotationMissionChatTagInfoListObject.annotationMissionChatTagInfoId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionChatTagInfoId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["CreateTime"].isNull())
					annotationMissionChatTagInfoListObject.createTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["CreateTime"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["ModifiedTime"].isNull())
					annotationMissionChatTagInfoListObject.modifiedTime = std::stol(dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["ModifiedTime"].asString());
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["InstanceId"].isNull())
					annotationMissionChatTagInfoListObject.instanceId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["InstanceId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionId"].isNull())
					annotationMissionChatTagInfoListObject.annotationMissionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionSessionId"].isNull())
					annotationMissionChatTagInfoListObject.annotationMissionSessionId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionSessionId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionChatId"].isNull())
					annotationMissionChatTagInfoListObject.annotationMissionChatId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionChatId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionTagInfoId"].isNull())
					annotationMissionChatTagInfoListObject.annotationMissionTagInfoId = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionTagInfoId"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionTagInfoName"].isNull())
					annotationMissionChatTagInfoListObject.annotationMissionTagInfoName = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["AnnotationMissionTagInfoName"].asString();
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["Delete"].isNull())
					annotationMissionChatTagInfoListObject._delete = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["Delete"].asString() == "true";
				if(!dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["Create"].isNull())
					annotationMissionChatTagInfoListObject.create = dataNodeAnnotationMissionSessionListAnnotationMissionSessionListItemAnnotationMissionChatListAnnotationMissionChatListItemAnnotationMissionChatTagInfoListAnnotationMissionChatTagInfoListItem["Create"].asString() == "true";
				annotationMissionChatListObject.annotationMissionChatTagInfoList.push_back(annotationMissionChatTagInfoListObject);
			}
			annotationMissionSessionListItemObject.annotationMissionChatList.push_back(annotationMissionChatListObject);
		}
		data_.annotationMissionSessionList.push_back(annotationMissionSessionListItemObject);
	}
	if(!value["Success"].isNull())
		success_ = value["Success"].asString() == "true";
	if(!value["Code"].isNull())
		code_ = value["Code"].asString();
	if(!value["Message"].isNull())
		message_ = value["Message"].asString();
	if(!value["HttpStatusCode"].isNull())
		httpStatusCode_ = std::stoi(value["HttpStatusCode"].asString());

}

std::string ListAnnotationMissionSessionResult::getMessage()const
{
	return message_;
}

int ListAnnotationMissionSessionResult::getHttpStatusCode()const
{
	return httpStatusCode_;
}

ListAnnotationMissionSessionResult::Data ListAnnotationMissionSessionResult::getData()const
{
	return data_;
}

std::string ListAnnotationMissionSessionResult::getCode()const
{
	return code_;
}

bool ListAnnotationMissionSessionResult::getSuccess()const
{
	return success_;
}

